### ISSUE TITLE
IllegalArgumentException: parameter must be a descendant of this view

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#111]
```
java.lang.IllegalArgumentException: parameter must be a descendant of this view
    at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:2513)
    at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:2450)
    at android.view.ViewRoot.scrollToRectOrFocus(ViewRoot.java:1432)
    at android.view.ViewRoot.draw(ViewRoot.java:1174)
    at android.view.ViewRoot.performTraversals(ViewRoot.java:1097)
    at android.view.ViewRoot.handleMessage(ViewRoot.java:1613)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4203)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
    at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `appeng...@brendandahl.com` on 18 Jun 2010 at 5:39

**Comment by GoogleCodeExporter** [comment]
```
Labels: Model-T-Mobile G1, OS-1.6, App-2.1; bump, rae
```

Original comment by `appeng...@brendandahl.com` on 18 Jun 2010 at 5:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 18 Jun 2010 at 9:58
- Changed title: **IllegalArgumentException: parameter must be a descendant of this view**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 18 Jun 2010 at 10:55
- Added labels: **Milestone-Release2.1.1**

**Comment by GoogleCodeExporter** [comment]
```
Issue 116 has been merged into this issue.
```

Original comment by `dahl.bre...@gmail.com` on 23 Jun 2010 at 12:25

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 24 Jul 2010 at 10:06
- Added labels: **Milestone-Release2.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 27 Aug 2010 at 3:02
- Added labels: **Milestone-Release2.2.1**
- Removed labels: **Milestone-Release2.2**

**Comment by GoogleCodeExporter** [comment]
```
This is still occurring in 2.2

Please fix!
```

Original comment by `swinefea...@gmail.com` on 1 Sep 2010 at 8:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 1 Sep 2010 at 8:18
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 3 Sep 2010 at 8:59
- Added labels: **App-2.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:32
- Added labels: **Milestone-Release2.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:43
- Added labels: **Milestone-Release3.0**
