### ISSUE TITLE
java.lang.OutOfMemoryError: bitmap size exceeds VM budget

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#117]
```
java.lang.OutOfMemoryError: bitmap size exceeds VM budget
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:468)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:435)
    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:340)
    at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:488)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:462)
    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:323)
    at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:346)
    at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:372)
    at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:371)
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:788)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:729)
    at android.content.res.Resources.loadDrawable(Resources.java:1690)
    at android.content.res.Resources.getDrawable(Resources.java:580)
    at android.view.View.setBackgroundResource(View.java:7186)
    at com.dahl.brendan.wordsearch.view.WordSearchActivity.setupViewGrid(WordSearchActivity.java:651)
    at com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController.restoreState(WordSearchActivityController.java:305)
    at com.dahl.brendan.wordsearch.view.WordSearchActivity.onCreate(WordSearchActivity.java:386)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3625)
    at android.app.ActivityThread.access$2300(ActivityThread.java:119)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1867)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4363)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
    at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `appeng...@brendandahl.com` on 29 Jun 2010 at 6:58

**Comment by GoogleCodeExporter** [comment]
```
Labels: Model-Droid, OS-2.1-update1, App-2.1; bump,
```

Original comment by `appeng...@brendandahl.com` on 29 Jun 2010 at 6:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 30 Jun 2010 at 10:15
- Changed title: **java.lang.OutOfMemoryError: bitmap size exceeds VM budget**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 6 Jul 2010 at 11:38
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Issue 119 has been merged into this issue.
```

Original comment by `dahl.bre...@gmail.com` on 9 Jul 2010 at 11:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 9 Jul 2010 at 11:59
- Added labels: **Model-T-MobilemyTouch3GSlide**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:32
- Added labels: **Milestone-Release2.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:43
- Added labels: **Milestone-Release3.0**

**Comment by GoogleCodeExporter** [comment]
```
Issue 136 has been merged into this issue.
```

Original comment by `dahl.bre...@gmail.com` on 10 Oct 2010 at 1:33

**Comment by GoogleCodeExporter** [comment]
```
Issue 137 has been merged into this issue.
```

Original comment by `dahl.bre...@gmail.com` on 9 Apr 2011 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
out of cheese error
```

Original comment by `dahl.bre...@gmail.com` on 9 Apr 2011 at 9:41
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 9 Apr 2011 at 10:08
- Changed state: **Verified**
