### ISSUE TITLE
stack trace

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#38]
```
Gen
Android Version: 1.6
App
Ver: 1.8.2
Package: com.dahl.brendan.wordsearch.view
Trace: java.lang.IllegalArgumentException: parameter must be a descendant of 
this view
       at 
android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:2513)
       at 
android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:2450)
       at android.view.ViewRoot.scrollToRectOrFocus(ViewRoot.java:1432)
       at android.view.ViewRoot.draw(ViewRoot.java:1174)
       at android.view.ViewRoot.performTraversals(ViewRoot.java:1097)
       at android.view.ViewRoot.handleMessage(ViewRoot.java:1613)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4203)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:79
1)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
       at dalvik.system.NativeStart.main(Native Method)

```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 13 Mar 2010 at 11:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Mar 2010 at 3:18
- Added labels: **Type-StackTrace**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
only reported on 1.6 (g1 and mytouch)
```

Original comment by `dahl.bre...@gmail.com` on 13 Mar 2010 at 3:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 14 Mar 2010 at 1:44
- Added labels: **Milestone-Release1.8.4**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 18 Mar 2010 at 12:19
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
