### ISSUE TITLE
stacktrace reset

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#39]
```
Gen
Android Version: 1.6
App
Ver: 1.8.2
Package: com.dahl.brendan.wordsearch.view
Trace: java.lang.NullPointerException
       at 
com.dahl.brendan.wordsearch.view.controller.TextViewGridController.reset(Text
ViewGridController.java:431)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController.setG
rid(WordSearchActivityController.java:215)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController.rest
oreState(WordSearchActivityController.java:201)
       at 
com.dahl.brendan.wordsearch.view.WordSearchActivity$1.run(WordSearchActivity.
java:189)
       at android.os.Handler.handleCallback(Handler.java:587)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4203)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:79
1)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
       at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 13 Mar 2010 at 11:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Mar 2010 at 3:18
- Added labels: **Type-StackTrace**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
affects 2x and 1.6 users
```

Original comment by `dahl.bre...@gmail.com` on 13 Mar 2010 at 3:23

**Comment by GoogleCodeExporter** [comment]
```
seems related


Gen
Phone Model: T-Mobile G1
Android Version: 1.6
App
Ver: 1.8.3
Package: com.dahl.brendan.wordsearch.view
Details:
Trace: java.lang.ArrayIndexOutOfBoundsException
       at com.dahl.brendan.wordsearch.model.Grid.getLetterAt(Grid.java:217)
       at 
com.dahl.brendan.wordsearch.view.controller.TextViewGridController.reset(TextVie
wGridCo
ntroller.java:438)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController.setGrid
(WordSe
archActivityController.java:215)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController.restore
State(W
ordSearchActivityController.java:199)
       at 
com.dahl.brendan.wordsearch.view.WordSearchActivity$1.run(WordSearchActivity.jav
a:192)
       at android.os.Handler.handleCallback(Handler.java:587)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4203)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
       at dalvik.system.NativeStart.main(Native Method)

```

Original comment by `dahl.bre...@gmail.com` on 14 Mar 2010 at 1:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 14 Mar 2010 at 1:41
- Added labels: **Priority-Critical**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 14 Mar 2010 at 1:44
- Added labels: **Milestone-Release1.8.4**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 18 Mar 2010 at 12:15
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
