### ISSUE TITLE
out of space issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#40]
```
Gen
Phone Model: T-Mobile G1
Android Version: 1.6
App
Ver: 1.8.3
Package: com.dahl.brendan.wordsearch.view
Details:
Trace: java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.dahl.brendan.wordsearch.view/com.dahl.brendan.wordsearch.vi
ew.WordSearchActivity}: android.database.sqlite.SQLiteFullException: error 
code 13: database or disk is full
       at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2401)
       at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
       at 
android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3502)
       at android.app.ActivityThread.access$2200(ActivityThread.java:116)
       at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1798)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4203)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:79
1)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
       at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteFullException: error code 13: 
database or disk is full
       at android.database.sqlite.SQLiteStatement.native_execute(Native 
Method)
       at 
android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:66)
       at 
android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.ja
va:1464)
       at 
android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1387)
       at 
com.google.android.apps.analytics.PersistentEventStore.storeUpdatedSession(Un
known Source)
       at 
com.google.android.apps.analytics.PersistentEventStore.putEvent(Unknown 
Source)
       at 
com.google.android.apps.analytics.GoogleAnalyticsTracker.createEvent(Unknown 
Source)
       at 
com.google.android.apps.analytics.GoogleAnalyticsTracker.trackPageView(Unknow
n Source)
       at 
com.dahl.brendan.wordsearch.view.WordSearchActivity.onCreate(WordSearchActivi
ty.java:176)
       at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
       at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
       ... 12 more

```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 13 Mar 2010 at 4:36

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 14 Mar 2010 at 1:44
- Added labels: **Milestone-Release1.9**, **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
fixed by try catch on all analytics code
```

Original comment by `dahl.bre...@gmail.com` on 15 Mar 2010 at 10:45
- Added labels: **Milestone-Release1.8.4**
- Removed labels: **Milestone-Release1.9**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 15 Mar 2010 at 10:47
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
