### ISSUE TITLE
unable to open database

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#42]
```
Gen
Phone Model: T-Mobile G1
Android Version: 1.6
App
Ver: 1.8.3
Package: com.dahl.brendan.wordsearch.view
Details:
Trace: java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.dahl.brendan.wordsearch.view/com.dahl.brendan.wordsearch.
view.WordSearchActivity}: android.database.sqlite.SQLiteException: unable 
to open database file
       at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2401)
       at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
       at android.app.ActivityThread.access$2100(ActivityThread.java:116)
       at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4203)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:
791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
       at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteException: unable to open database 
file
       at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
       at 
android.database.sqlite.SQLiteDatabase.<init>(SQLiteDatabase.java:1584)
       at 
android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:638
)
       at 
android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelp
er.java:168)
       at 
com.google.android.apps.analytics.PersistentEventStore.getNumStoredEvents(U
nknown Source)
       at 
com.google.android.apps.analytics.PersistentEventStore.startNewVisit(Unknow
n Source)
       at 
com.google.android.apps.analytics.GoogleAnalyticsTracker.start(Unknown 
Source)
       at 
com.google.android.apps.analytics.GoogleAnalyticsTracker.start(Unknown 
Source)
       at 
com.dahl.brendan.wordsearch.view.WordSearchActivity.onCreate(WordSearchActi
vity.java:175)
       at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
       at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
       ... 11 more

```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 15 Mar 2010 at 12:00

**Comment by GoogleCodeExporter** [comment]
```
fixed by try catch on all analytics code
```

Original comment by `dahl.bre...@gmail.com` on 15 Mar 2010 at 10:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 15 Mar 2010 at 10:47
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
