### ISSUE TITLE
current high score is null

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#44]
```
Gen
Phone Model: T-Mobile G1
Android Version: 1.6
App
Ver: 1.8.3
Package: com.dahl.brendan.wordsearch.view
Details:
Trace: java.lang.RuntimeException: currentHighScore is null
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController.ge
tCurrentHighScore(WordSearchActivityController.java:145)
       at 
com.dahl.brendan.wordsearch.view.WordSearchActivity.onPrepareDialog(WordSea
rchActivity.java:297)
       at android.app.Activity.showDialog(Activity.java:2412)
       at 
com.dahl.brendan.wordsearch.view.WordSearchActivity$DialogHighScoresShowLis
tener.onClick(WordSearchActivity.java:88)
       at 
com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertC
ontroller.java:158)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4203)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:
791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
       at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 16 Mar 2010 at 1:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 18 Mar 2010 at 12:18
- Added labels: **Milestone-Release1.8.5**
- Removed labels: **Milestone-Release1.8.4**

**Comment by GoogleCodeExporter** [comment]
```
this is because android will restore any managed dialogs whether they were 
showing or 
now when activity was saved; as such data maybe missing when on prepare is 
called; this 
is solved by calling removeDialog(int) when the dialog is done (canceled or 
dismissed)?
```

Original comment by `dahl.bre...@gmail.com` on 20 Mar 2010 at 10:38
- Added labels: **Milestone-Release1.8.6**
- Removed labels: **Milestone-Release1.8.5**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 21 Mar 2010 at 12:20
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
