### ISSUE TITLE
view flipper

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#45]
```
Gen
Phone Model: T-Mobile G1
Android Version: 2.1
App
Ver: 1.8.3
Package: com.dahl.brendan.wordsearch.view
Details:
Trace: java.lang.IllegalArgumentException: Receiver not registered: 
android.widget.ViewFlipper$1@43e05200
       at 
android.app.ActivityThread$PackageInfo.forgetReceiverDispatcher(ActivityThrea
d.java:667)
       at 
android.app.ApplicationContext.unregisterReceiver(ApplicationContext.java:747
)
       at 
android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:321)
       at 
android.widget.ViewFlipper.onDetachedFromWindow(ViewFlipper.java:104)
       at android.view.View.dispatchDetachedFromWindow(View.java:5854)
       at 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1076)
       at 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1074)
       at 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1074)
       at 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1074)
       at 
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1074)
       at 
android.view.ViewRoot.dispatchDetachedFromWindow(ViewRoot.java:1570)
       at android.view.ViewRoot.doDie(ViewRoot.java:2556)
       at android.view.ViewRoot.die(ViewRoot.java:2526)
       at 
android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:218
)
       at 
android.view.Window$LocalWindowManager.removeViewImmediate(Window.java:436)
       at 
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3498)
       at 
android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3599)
       at android.app.ActivityThread.access$2300(ActivityThread.java:119)
       at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1867)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4363)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:86
0)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
       at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 17 Mar 2010 at 11:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 18 Mar 2010 at 12:17
- Added labels: **Milestone-Release1.9**

**Comment by GoogleCodeExporter** [comment]
```
related to http://code.google.com/p/android/issues/detail?id=6191

only 2.1+ and can be resolved by using framelayout instead of viewflipper
```

Original comment by `dahl.bre...@gmail.com` on 8 Apr 2010 at 11:05
- Changed state: **Fixed**
- Added labels: **Milestone-Release2.0**
- Removed labels: **Milestone-Release1.9**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 27 Apr 2010 at 11:13
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
