### ISSUE TITLE
High score to bundle crashing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#48]
```
Trace: java.lang.RuntimeException: Unable to pause activity 
{com.dahl.brendan.wordsearch.view/com.dahl.brendan.wordsearch.view.WordSear
chActivity}: java.lang.NullPointerException
       at 
android.app.ActivityThread.performPauseActivity(ActivityThread.java:3162)
       at 
android.app.ActivityThread.performPauseActivity(ActivityThread.java:3119)
       at 
android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3596)
       at android.app.ActivityThread.access$2300(ActivityThread.java:119)
       at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1867)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:4363)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:521)
       at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:
860)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
       at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
       at 
com.dahl.brendan.wordsearch.model.HighScore.toBundle(HighScore.java:75)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController.sa
veState(WordSearchActivityController.java:284)
       at 
com.dahl.brendan.wordsearch.view.WordSearchActivity.onSaveInstanceState(Wor
dSearchActivity.java:589)
       at android.app.Activity.performSaveInstanceState(Activity.java:1022)
       at 
android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation
.java:1180)
       at 
android.app.ActivityThread.performPauseActivity(ActivityThread.java:3144)
       ... 12 more

```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 1 May 2010 at 12:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 25 May 2010 at 12:33
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
