### ISSUE TITLE
game over no HS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#49]
```
Gen
Phone Model: Droid
Android Version: 2.1-update1
App Ver: 1.9
Package: com.dahl.brendan.wordsearch.view
IP: 97.50.226.171
Details:
Trace: java.lang.RuntimeException: An error occured while executing 
doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:200)
       at 
java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at 
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1
068)
       at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:
561)
       at java.lang.Thread.run(Thread.java:1096)
Caused by: java.lang.NullPointerException
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController$Ga
meOverTask.doInBackground(WordSearchActivityController.java:116)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController$Ga
meOverTask.doInBackground(WordSearchActivityController.java:1)
       at android.os.AsyncTask$2.call(AsyncTask.java:185)
       at 
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       ... 4 more
```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 7 May 2010 at 12:48

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 25 May 2010 at 12:33
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
