### ISSUE TITLE
client connections closed?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#50]
```
Trace: java.lang.RuntimeException: An error occured while executing 
doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:200)
       at 
java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:234)
       at 
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:258)
       at java.util.concurrent.FutureTask.run(FutureTask.java:122)
       at 
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.j
ava:648)
       at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:
673)
       at java.lang.Thread.run(Thread.java:1060)
Caused by: java.lang.IllegalStateException: Connection pool shut down.
       at 
org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolBy
Route.java:284)
       at 
org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRo
ute.java:238)
       at 
org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection
(ThreadSafeClientConnManager.java:175)
       at 
org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDi
rector.java:325)
       at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.j
ava:555)
       at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.j
ava:487)
       at 
org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.j
ava:465)
       at 
com.dahl.brendan.wordsearch.util.AndroidHttpClient.execute(AndroidHttpClien
t.java:154)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController$Ga
meOverTask.doInBackground(WordSearchActivityController.java:97)
       at 
com.dahl.brendan.wordsearch.view.controller.WordSearchActivityController$Ga
meOverTask.doInBackground(WordSearchActivityController.java:1)
       at android.os.AsyncTask$2.call(AsyncTask.java:185)
       at 
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:256)
       ... 4 more
```

Original issue reported on code.google.com by `dahl.bre...@gmail.com` on 7 May 2010 at 1:07

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 25 May 2010 at 12:33
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 13 Jun 2010 at 12:46
- Added labels: **Type-Defect**
