### ISSUE TITLE
java.lang.IllegalArgumentException: View not attached to window manager

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#81]
```
java.lang.IllegalArgumentException: View not attached to window manager
    at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:355)
    at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:200)
    at android.view.Window$LocalWindowManager.removeView(Window.java:432)
    at android.app.Dialog.dismissDialog(Dialog.java:280)
    at android.app.Dialog.access$000(Dialog.java:73)
    at android.app.Dialog$1.run(Dialog.java:109)
    at android.app.Dialog.dismiss(Dialog.java:264)
    at com.dahl.brendan.wordsearch.view.WordSearchActivity$StartHighScoreGlobalTask.onPostExecute(WordSearchActivity.java:84)
    at com.dahl.brendan.wordsearch.view.WordSearchActivity$StartHighScoreGlobalTask.onPostExecute(WordSearchActivity.java:1)
    at android.os.AsyncTask.finish(AsyncTask.java:417)
    at android.os.AsyncTask.access$300(AsyncTask.java:127)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4363)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
    at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `appeng...@brendandahl.com` on 11 Jun 2010 at 1:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 11 Jun 2010 at 10:18
- Changed title: **java.lang.IllegalArgumentException: View not attached to window manager**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 14 Jun 2010 at 11:58
- Added labels: **Milestone-Release2.1.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 15 Jun 2010 at 1:31
- Added labels: **App-2.0.1**, **OS-2.1-update1**
- Removed labels: **Version-Android-2.1-update1**, **Version-Application-2.0.1**

**Comment by GoogleCodeExporter** [comment]
```
Issue 115 has been merged into this issue.
```

Original comment by `dahl.bre...@gmail.com` on 23 Jun 2010 at 12:24

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 10 Jul 2010 at 5:08
- Added labels: **App-2.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 24 Jul 2010 at 10:06
- Added labels: **Milestone-Release2.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 27 Aug 2010 at 3:03
- Added labels: **Milestone-Release2.2.1**
- Removed labels: **Milestone-Release2.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:32
- Added labels: **Milestone-Release2.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:43
- Added labels: **Milestone-Release3.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 9 Apr 2011 at 6:40
- Changed state: **Fixed**
