### ISSUE TITLE
java.lang.NullPointerException: point: 8,10; delta: 0,0; length: 9

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dakshika/wordsearch-android#82]
```
java.lang.NullPointerException: point: 8,10; delta: 0,0; length: 9
    at com.dahl.brendan.wordsearch.view.controller.TextViewGridController.selectionPaint(TextViewGridController.java:348)
    at com.dahl.brendan.wordsearch.view.controller.TextViewGridController.selectionEnd(TextViewGridController.java:319)
    at com.dahl.brendan.wordsearch.view.controller.TextViewGridController.selectionStartEnd(TextViewGridController.java:385)
    at com.dahl.brendan.wordsearch.view.controller.TextViewGridController.handleTextViewEventClick(TextViewGridController.java:183)
    at com.dahl.brendan.wordsearch.view.controller.TextViewGridController.run(TextViewGridController.java:164)
    at java.lang.Thread.run(Thread.java:1096)
```

Original issue reported on code.google.com by `appeng...@brendandahl.com` on 11 Jun 2010 at 3:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 11 Jun 2010 at 10:18
- Changed title: **java.lang.NullPointerException: point: 8,10; delta: 0,0; length: 9**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 14 Jun 2010 at 11:58
- Added labels: **Milestone-Release2.1.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 15 Jun 2010 at 1:31
- Added labels: **App-2.0.1**, **OS-2.1-update1**
- Removed labels: **Version-Android-2.1-update1**, **Version-Application-2.0.1**

**Comment by GoogleCodeExporter** [comment]
```
Issue 108 has been merged into this issue.
```

Original comment by `dahl.bre...@gmail.com` on 17 Jun 2010 at 11:53

**Comment by GoogleCodeExporter** [comment]
```
Issue 105 has been merged into this issue.
```

Original comment by `dahl.bre...@gmail.com` on 17 Jun 2010 at 11:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 24 Jul 2010 at 10:06
- Added labels: **Milestone-Release2.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 27 Aug 2010 at 3:03
- Added labels: **Milestone-Release2.2.1**
- Removed labels: **Milestone-Release2.2**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 3 Sep 2010 at 9:04
- Added labels: **App-2.1**, **Model-T-MobileG1**, **OS-1.6**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:32
- Added labels: **Milestone-Release2.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 5 Sep 2010 at 1:40
- Added labels: **Milestone-Release2.4**
- Removed labels: **Milestone-Release2.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `dahl.bre...@gmail.com` on 7 Sep 2010 at 12:51
- Changed state: **Verified**
- Added labels: **Milestone-Release2.3**
- Removed labels: **Milestone-Release2.4**
